/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaPresentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class frmCafeTinto extends javax.swing.JFrame {

    /**
     * Creates new form frmCafeTinto
     */
    public frmCafeTinto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        txtValorRecolectado = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        btnLeer = new javax.swing.JButton();
        btnEscribir = new javax.swing.JButton();
        btnMetodo1 = new javax.swing.JButton();
        btnMetodo2 = new javax.swing.JButton();
        btnMetodo3 = new javax.swing.JButton();
        btnMetodo4 = new javax.swing.JButton();
        btnMetodo5 = new javax.swing.JButton();
        btnMetodo6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });

        btnLeer.setText("Leer");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });

        btnEscribir.setText("Escribir");
        btnEscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscribirActionPerformed(evt);
            }
        });

        btnMetodo1.setText("Metodo 1");
        btnMetodo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo1ActionPerformed(evt);
            }
        });

        btnMetodo2.setText("Metodo 2");
        btnMetodo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo2ActionPerformed(evt);
            }
        });

        btnMetodo3.setText("Metodo 3");
        btnMetodo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo3ActionPerformed(evt);
            }
        });

        btnMetodo4.setText("Metodo 4");
        btnMetodo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo4ActionPerformed(evt);
            }
        });

        btnMetodo5.setText("Metodo 5");
        btnMetodo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo5ActionPerformed(evt);
            }
        });

        btnMetodo6.setText("Metodo 6");
        btnMetodo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodo6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Javanese Text", 0, 18)); // NOI18N
        jLabel1.setText("Cafe Tinto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValorRecolectado)
                    .addComponent(txtNombre)
                    .addComponent(txtCosto)
                    .addComponent(txtCantidad)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMetodo4)
                            .addComponent(btnMetodo1))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMetodo5)
                            .addComponent(btnMetodo2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMetodo3)
                            .addComponent(btnMetodo6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtValorRecolectado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEscribir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMetodo1)
                    .addComponent(btnMetodo2)
                    .addComponent(btnMetodo3))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMetodo4)
                    .addComponent(btnMetodo5)
                    .addComponent(btnMetodo6))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoActionPerformed
    CapaNegocio.CafeTinto cafeTinto = new CapaNegocio.CafeTinto();
    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        // TODO add your handling code here:
        String Valor_Recolectado = txtValorRecolectado.getText();
        String Nombre = txtNombre.getText();
        String Costo = txtCosto.getText();
        String Cantidad = txtCantidad.getText();
        String Marca = txtMarca.getText();
        //Levar los datos
        cafeTinto.setValor_recolectado(Valor_Recolectado);
        cafeTinto.setNombre(Nombre);
        cafeTinto.setCosto(Costo);
        cafeTinto.setCantidad(Cantidad);
        cafeTinto.setMarca(Marca);
        JOptionPane.showMessageDialog(rootPane, "El objeto se escribio correctamente");
    }//GEN-LAST:event_btnLeerActionPerformed

    private void btnEscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscribirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "ValorRecolectado: " + cafeTinto.getValor_recolectado() + 
                                      "\nNombre: " + cafeTinto.getNombre() + 
                                        "\nCosto: " + cafeTinto.getCosto() + 
                                        "\nCantidad: " + cafeTinto.getCantidad() + 
                                        "\nMarca: " + cafeTinto.getMarca());
    }//GEN-LAST:event_btnEscribirActionPerformed

    private void btnMetodo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, String.valueOf(cafeTinto.RecibirMoneda()));
    }//GEN-LAST:event_btnMetodo1ActionPerformed

    private void btnMetodo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, String.valueOf(cafeTinto.CancelarOperacion()));
    }//GEN-LAST:event_btnMetodo2ActionPerformed

    private void btnMetodo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, String.valueOf(cafeTinto.ServirProducto()));
    }//GEN-LAST:event_btnMetodo3ActionPerformed

    private void btnMetodo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo4ActionPerformed
        // TODO add your handling code here: 
        JOptionPane.showMessageDialog(rootPane, String.valueOf(cafeTinto.EntregarVuelto()));
    }//GEN-LAST:event_btnMetodo4ActionPerformed

    private void btnMetodo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, String.valueOf(cafeTinto.ElegirProducto()));
    }//GEN-LAST:event_btnMetodo5ActionPerformed

    private void btnMetodo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodo6ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, String.valueOf(cafeTinto.Escogercantidad()));
    }//GEN-LAST:event_btnMetodo6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCafeTinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCafeTinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCafeTinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCafeTinto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCafeTinto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEscribir;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnMetodo1;
    private javax.swing.JButton btnMetodo2;
    private javax.swing.JButton btnMetodo3;
    private javax.swing.JButton btnMetodo4;
    private javax.swing.JButton btnMetodo5;
    private javax.swing.JButton btnMetodo6;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtValorRecolectado;
    // End of variables declaration//GEN-END:variables
}
